<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lawrence Lin">
<meta name="dcterms.date" content="2026-05-17">

<title>Poisson Regression and Maximum Likelihood Estimation – Lawrence Lin</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-89ba6b723c0026cab07b5b492f14f291.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Lawrence Lin</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Experience.html"> 
<span class="menu-text">Experience</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#exploring-the-data" id="toc-exploring-the-data" class="nav-link" data-scroll-target="#exploring-the-data">Exploring the Data</a></li>
  <li><a href="#a-simple-poisson-model-via-maximum-likelihood" id="toc-a-simple-poisson-model-via-maximum-likelihood" class="nav-link" data-scroll-target="#a-simple-poisson-model-via-maximum-likelihood">A Simple Poisson Model via Maximum Likelihood</a></li>
  <li><a href="#poisson-regression" id="toc-poisson-regression" class="nav-link" data-scroll-target="#poisson-regression">Poisson Regression</a></li>
  <li><a href="#the-effect-of-blueprintys-software" id="toc-the-effect-of-blueprintys-software" class="nav-link" data-scroll-target="#the-effect-of-blueprintys-software">The Effect of Blueprinty’s Software</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Poisson Regression and Maximum Likelihood Estimation</h1>
<p class="subtitle lead">A Case Study of Blueprinty’s Software and Patent Awards</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lawrence Lin </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 17, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Blueprinty is a small software company that builds tools for engineering firms preparing blueprint materials for patent applications. Its marketing team wants to make a strong claim: firms that use Blueprinty’s software are more successful at getting patents approved.</p>
<p>Ideally, we would evaluate this claim with before-and-after data. For example, we would want to observe each firm’s patent success rate before adopting Blueprinty and again after adopting it. That kind of data would make it easier to isolate whether the software itself changed the firm’s patent outcomes. Unfortunately, Blueprinty does not have that dataset.</p>
<p>Instead, Blueprinty has collected cross-sectional data on 1,500 mature engineering firms. For each firm, the dataset records the number of patents awarded over the past five years, the firm’s region, the firm’s age, and whether the firm is a Blueprinty customer.</p>
<p>This makes the analysis interesting but also challenging. If Blueprinty customers have more patents on average, that does not automatically mean the software caused the difference. Customers are not randomly selected. They may be older, located in regions with stronger engineering ecosystems, or different in other ways that also affect patent output. The goal of this post is to use Poisson regression and maximum likelihood estimation to estimate the relationship between Blueprinty usage and patent counts while accounting for observable differences across firms.</p>
</div>
</div>
</div>
</section>
<section id="exploring-the-data" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-data">Exploring the Data</h2>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Before estimating the model, I first inspect the data to understand how patent outcomes differ between Blueprinty customers and non-customers. The dataset contains 1,500 mature engineering firms and records each firm’s number of patents awarded over the last five years, region, age, and whether the firm is a Blueprinty customer.</p>
<div id="5f77f5b7" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<style type="text/css">
</style>

<div id="T_26f83" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_26f83-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary Statistics by Customer Status
</figcaption>
<div aria-describedby="T_26f83-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_26f83" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_26f83_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Customer status</th>
<th id="T_26f83_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Firms</th>
<th id="T_26f83_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Mean patents</th>
<th id="T_26f83_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Median patents</th>
<th id="T_26f83_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">Mean firm age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_26f83_row0_col0" class="data row0 col0">Non-customer</td>
<td id="T_26f83_row0_col1" class="data row0 col1">1019</td>
<td id="T_26f83_row0_col2" class="data row0 col2">3.47</td>
<td id="T_26f83_row0_col3" class="data row0 col3">3.00</td>
<td id="T_26f83_row0_col4" class="data row0 col4">26.10</td>
</tr>
<tr class="even">
<td id="T_26f83_row1_col0" class="data row1 col0">Blueprinty customer</td>
<td id="T_26f83_row1_col1" class="data row1 col1">481</td>
<td id="T_26f83_row1_col2" class="data row1 col2">4.13</td>
<td id="T_26f83_row1_col3" class="data row1 col3">4.00</td>
<td id="T_26f83_row1_col4" class="data row1 col4">26.90</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p>Blueprinty customers receive more patents on average than non-customers. Non-customers receive about 3.47 patents over the five-year period, while Blueprinty customers receive about 4.13 patents. This raw difference is consistent with Blueprinty’s marketing claim, but it is only descriptive. It does not yet prove that the software itself caused the difference.</p>
<div id="1f3eb011" class="cell" data-fig-height="3.4" data-fig-width="6" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-4-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="648" height="421"></p>
</figure>
</div>
</div>
</div>
<p>The two histograms have similar shapes, with most firms receiving a relatively small number of patents. However, the customer distribution is shifted slightly to the right. This means Blueprinty customers are somewhat more likely to have higher patent counts, which explains why their average number of patents is higher.</p>
<p>However, customer status is not randomly assigned. Firms that choose to use Blueprinty may differ from non-customers in ways that also affect patent output. Two especially important firm characteristics are region and age.</p>
<div id="9c9e33af" class="cell" data-fig-height="3.8" data-fig-width="6" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-5-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="715" height="449"></p>
</figure>
</div>
</div>
</div>
<p>The regional composition differs substantially between customers and non-customers. Blueprinty customers are much more concentrated in the Northeast, while non-customers are more evenly distributed across regions. This matters because region could be related to patent activity. For example, some regions may have stronger engineering labor markets, more patent attorneys, better university networks, or more innovative firms. If firms in one region tend to receive more patents anyway, then part of the raw customer advantage could reflect regional differences rather than the effect of Blueprinty’s software.</p>
<div id="e3dd6ff8" class="cell" data-fig-height="3.4" data-fig-width="6" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-6-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="637" height="421"></p>
</figure>
</div>
</div>
</div>
<p>The age distributions are fairly similar, but Blueprinty customers are slightly older on average. Non-customers have an average age of about 26.10 years, while Blueprinty customers have an average age of about 26.90 years. This difference is not huge, but age may still matter because older firms could have more experience, larger engineering teams, and more developed patent pipelines.</p>
<p>Overall, the exploratory analysis suggests that Blueprinty customers have higher patent counts, but they also differ from non-customers in region and, to a smaller extent, firm age. The regression model that follows should therefore control for these characteristics before interpreting the relationship between Blueprinty usage and patent outcomes.</p>
</div>
</div>
</div>
</section>
<section id="a-simple-poisson-model-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="a-simple-poisson-model-via-maximum-likelihood">A Simple Poisson Model via Maximum Likelihood</h2>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Patent awards are count data. A firm can receive 0, 1, 2, or more patents over a five-year period, but it cannot receive a negative number of patents or a fractional number of patents. Because of this, a normal distribution is not the most natural choice for modeling the outcome. A Poisson distribution is a better starting point because it is designed for non-negative integer outcomes.</p>
<p>To begin, I use a very simple Poisson model where every firm has the same expected patent count, <span class="math inline">\(\lambda\)</span>:</p>
<p><span class="math display">\[
Y_i \sim \text{Poisson}(\lambda)
\]</span></p>
<p>For a single firm, the probability of observing patent count <span class="math inline">\(Y_i\)</span> is:</p>
<p><span class="math display">\[
f(Y_i|\lambda) = \frac{e^{-\lambda}\lambda^{Y_i}}{Y_i!}
\]</span></p>
<p>Assuming the observations are independent and identically distributed, the joint likelihood for all <span class="math inline">\(n\)</span> firms is the product of the individual probabilities:</p>
<p><span class="math display">\[
L(\lambda|Y)
=
\prod_{i=1}^{n}
\frac{e^{-\lambda}\lambda^{Y_i}}{Y_i!}
\]</span></p>
<p>This can be simplified as:</p>
<p><span class="math display">\[
L(\lambda|Y)
=
\frac{
e^{-n\lambda}
\lambda^{\sum_{i=1}^{n}Y_i}
}{
\prod_{i=1}^{n}Y_i!
}
\]</span></p>
<p>Taking logs gives the log-likelihood:</p>
<p><span class="math display">\[
\ell(\lambda|Y)
=
-n\lambda
+
\left(\sum_{i=1}^{n}Y_i\right)\log(\lambda)
-
\sum_{i=1}^{n}\log(Y_i!)
\]</span></p>
<p>The last term, <span class="math inline">\(\sum_{i=1}^{n}\log(Y_i!)\)</span>, does not depend on <span class="math inline">\(\lambda\)</span>. It changes the height of the log-likelihood curve, but it does not change the value of <span class="math inline">\(\lambda\)</span> that maximizes the function.</p>
<p>The log-likelihood function evaluates how well each possible value of <span class="math inline">\(\lambda\)</span> fits the observed patent counts. I use <code>gammaln(Y + 1)</code> rather than directly computing <span class="math inline">\(\log(Y_i!)\)</span> because it is more numerically stable.</p>
<p>Next, I evaluate the log-likelihood over a grid of possible <span class="math inline">\(\lambda\)</span> values and plot the result.</p>
<div id="a36bd56c" class="cell" data-fig-height="3.6" data-fig-width="6" data-execution_count="7">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-8-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="714" height="425"></p>
</figure>
</div>
</div>
</div>
<p>The log-likelihood curve reaches its maximum near <span class="math inline">\(\lambda = 3.685\)</span>. Visually, the maximum likelihood estimate is the value of <span class="math inline">\(\lambda\)</span> where the curve is highest. In this simple model, that value is the average number of patents in the sample.</p>
<p>We can also show this result analytically. Starting from the log-likelihood,</p>
<p><span class="math display">\[
\ell(\lambda|Y)
=
-n\lambda
+
\left(\sum_{i=1}^{n}Y_i\right)\log(\lambda)
-
\sum_{i=1}^{n}\log(Y_i!)
\]</span></p>
<p>take the first derivative with respect to <span class="math inline">\(\lambda\)</span>:</p>
<p><span class="math display">\[
\frac{\partial \ell}{\partial \lambda}
=
-n
+
\frac{\sum_{i=1}^{n}Y_i}{\lambda}
\]</span></p>
<p>Set the derivative equal to zero:</p>
<p><span class="math display">\[
-n
+
\frac{\sum_{i=1}^{n}Y_i}{\lambda}
=
0
\]</span></p>
<p>Solving for <span class="math inline">\(\lambda\)</span> gives:</p>
<p><span class="math display">\[
\hat{\lambda}_{MLE}
=
\frac{1}{n}\sum_{i=1}^{n}Y_i
=
\bar{Y}
\]</span></p>
<p>This result makes intuitive sense. The mean of a Poisson distribution is <span class="math inline">\(\lambda\)</span>, so the best-fitting single-rate Poisson model chooses <span class="math inline">\(\lambda\)</span> to match the observed average patent count.</p>
<p>Finally, I find the MLE numerically by maximizing the log-likelihood function. Since <code>scipy.optimize</code> minimizes functions by default, I minimize the negative log-likelihood.</p>
<div id="f629db80" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<style type="text/css">
</style>

<div id="T_57a1e" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_57a1e-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Simple Poisson Model Estimate
</figcaption>
<div aria-describedby="T_57a1e-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_57a1e" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_57a1e_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Method</th>
<th id="T_57a1e_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Estimate of lambda</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_57a1e_row0_col0" class="data row0 col0">Numerical MLE using scipy.optimize</td>
<td id="T_57a1e_row0_col1" class="data row0 col1">3.6847</td>
</tr>
<tr class="even">
<td id="T_57a1e_row1_col0" class="data row1 col0">Sample mean</td>
<td id="T_57a1e_row1_col1" class="data row1 col1">3.6847</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p>The numerical MLE and the sample mean are nearly identical. This confirms the analytical result: for a simple Poisson model with one common rate parameter, the maximum likelihood estimate of <span class="math inline">\(\lambda\)</span> is the average number of patents in the data.</p>
<p>In this dataset, the estimated value is approximately:</p>
<p><span class="math display">\[
\hat{\lambda}_{MLE} = 3.685
\]</span></p>
<p>This means that if every firm were modeled as coming from the same Poisson distribution, the model would predict about 3.685 patents per firm over the five-year period. This is a useful starting point, but it is too simple for the main research question because it ignores customer status, age, and region. The next section extends the model to Poisson regression, where each firm can have its own expected patent count based on its characteristics.</p>
</div>
</div>
</div>
</section>
<section id="poisson-regression" class="level2">
<h2 class="anchored" data-anchor-id="poisson-regression">Poisson Regression</h2>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div style="direction: ltr; padding: 1rem;">
<p>The simple Poisson model assumed that every firm had the same expected number of patents, <span class="math inline">\(\lambda\)</span>. That was useful for understanding the basic maximum likelihood idea, but it is too restrictive for the main business question. Firms differ in age, region, and whether they use Blueprinty’s software, so their expected patent counts should be allowed to differ as well.</p>
<p>To do this, I use a Poisson regression model:</p>
<p><span class="math display">\[
Y_i \sim \text{Poisson}(\lambda_i)
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\lambda_i = \exp(X_i'\beta)
\]</span></p>
<p>The term <span class="math inline">\(X_i'\beta\)</span> is a linear combination of firm characteristics. It can be any real number, positive or negative. However, <span class="math inline">\(\lambda_i\)</span> is an expected count, so it must always be positive. The exponential function solves this problem because <span class="math inline">\(\exp(X_i'\beta)\)</span> is always positive.</p>
<p>In this model, the covariates include firm age, age squared, region indicators, and whether the firm is a Blueprinty customer. I include age squared because the relationship between firm age and patent output is unlikely to be perfectly linear. For example, patenting may rise as firms mature but eventually level off. I include region indicators because firms in different regions may face different innovation environments. One region must be omitted as the baseline category to avoid perfect collinearity with the intercept; here, Midwest is the omitted region.</p>
<p>For firm <span class="math inline">\(i\)</span>, the Poisson log-likelihood is:</p>
<p><span class="math display">\[
\ell_i(\beta)
=
Y_i X_i'\beta
-
\exp(X_i'\beta)
-
\log(Y_i!)
\]</span></p>
<p>Therefore, the full sample log-likelihood is:</p>
<p><span class="math display">\[
\ell(\beta)
=
\sum_{i=1}^{n}
\left[
Y_i X_i'\beta
-
\exp(X_i'\beta)
-
\log(Y_i!)
\right]
\]</span></p>
<p>The likelihood was coded directly in Python using the log-likelihood expression above, and then maximized with <code>scipy.optimize.minimize</code>.</p>
<p>I estimate the model by minimizing the negative log-likelihood. The Hessian of the negative log-likelihood is used to compute standard errors. Since the model is estimated by maximum likelihood, the inverse Hessian provides an estimate of the covariance matrix for the coefficient estimates.</p>
<div id="88f2efc8" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<style type="text/css">
</style>

<div id="T_bacdc" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_bacdc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Poisson Regression Estimated by Maximum Likelihood
</figcaption>
<div aria-describedby="T_bacdc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_bacdc" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_bacdc_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Variable</th>
<th id="T_bacdc_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Coefficient</th>
<th id="T_bacdc_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Std. Error</th>
<th id="T_bacdc_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Incidence Rate Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_bacdc_row0_col0" class="data row0 col0">Intercept</td>
<td id="T_bacdc_row0_col1" class="data row0 col1">-0.5089</td>
<td id="T_bacdc_row0_col2" class="data row0 col2">0.1832</td>
<td id="T_bacdc_row0_col3" class="data row0 col3">0.601</td>
</tr>
<tr class="even">
<td id="T_bacdc_row1_col0" class="data row1 col0">Age</td>
<td id="T_bacdc_row1_col1" class="data row1 col1">0.1486</td>
<td id="T_bacdc_row1_col2" class="data row1 col2">0.0139</td>
<td id="T_bacdc_row1_col3" class="data row1 col3">1.160</td>
</tr>
<tr class="odd">
<td id="T_bacdc_row2_col0" class="data row2 col0">Age squared</td>
<td id="T_bacdc_row2_col1" class="data row2 col1">-0.0030</td>
<td id="T_bacdc_row2_col2" class="data row2 col2">0.0003</td>
<td id="T_bacdc_row2_col3" class="data row2 col3">0.997</td>
</tr>
<tr class="even">
<td id="T_bacdc_row3_col0" class="data row3 col0">Region_Northeast</td>
<td id="T_bacdc_row3_col1" class="data row3 col1">0.0292</td>
<td id="T_bacdc_row3_col2" class="data row3 col2">0.0436</td>
<td id="T_bacdc_row3_col3" class="data row3 col3">1.030</td>
</tr>
<tr class="odd">
<td id="T_bacdc_row4_col0" class="data row4 col0">Region_Northwest</td>
<td id="T_bacdc_row4_col1" class="data row4 col1">-0.0176</td>
<td id="T_bacdc_row4_col2" class="data row4 col2">0.0538</td>
<td id="T_bacdc_row4_col3" class="data row4 col3">0.983</td>
</tr>
<tr class="even">
<td id="T_bacdc_row5_col0" class="data row5 col0">Region_South</td>
<td id="T_bacdc_row5_col1" class="data row5 col1">0.0566</td>
<td id="T_bacdc_row5_col2" class="data row5 col2">0.0527</td>
<td id="T_bacdc_row5_col3" class="data row5 col3">1.058</td>
</tr>
<tr class="odd">
<td id="T_bacdc_row6_col0" class="data row6 col0">Region_Southwest</td>
<td id="T_bacdc_row6_col1" class="data row6 col1">0.0506</td>
<td id="T_bacdc_row6_col2" class="data row6 col2">0.0472</td>
<td id="T_bacdc_row6_col3" class="data row6 col3">1.052</td>
</tr>
<tr class="even">
<td id="T_bacdc_row7_col0" class="data row7 col0">Blueprinty customer</td>
<td id="T_bacdc_row7_col1" class="data row7 col1">0.2076</td>
<td id="T_bacdc_row7_col2" class="data row7 col2">0.0309</td>
<td id="T_bacdc_row7_col3" class="data row7 col3">1.231</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p>The coefficient table reports the estimated effect of each variable on the log expected patent count. The incidence rate ratio column exponentiates each coefficient, which makes the results easier to interpret. A value above 1 means the variable is associated with a higher expected patent count, while a value below 1 means it is associated with a lower expected patent count.</p>
<p>Next, I check the results against <code>statsmodels</code> using the same outcome variable and covariate matrix.</p>
<div id="5ed65234" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<style type="text/css">
</style>

<div id="T_01141" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_01141-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Checking the Custom MLE Against statsmodels GLM
</figcaption>
<div aria-describedby="T_01141-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_01141" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_01141_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Variable</th>
<th id="T_01141_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">MLE coefficient</th>
<th id="T_01141_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">GLM coefficient</th>
<th id="T_01141_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">MLE std. error</th>
<th id="T_01141_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">GLM std. error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_01141_row0_col0" class="data row0 col0">Intercept</td>
<td id="T_01141_row0_col1" class="data row0 col1">-0.5089</td>
<td id="T_01141_row0_col2" class="data row0 col2">-0.5089</td>
<td id="T_01141_row0_col3" class="data row0 col3">0.1832</td>
<td id="T_01141_row0_col4" class="data row0 col4">0.1832</td>
</tr>
<tr class="even">
<td id="T_01141_row1_col0" class="data row1 col0">Age</td>
<td id="T_01141_row1_col1" class="data row1 col1">0.1486</td>
<td id="T_01141_row1_col2" class="data row1 col2">0.1486</td>
<td id="T_01141_row1_col3" class="data row1 col3">0.0139</td>
<td id="T_01141_row1_col4" class="data row1 col4">0.0139</td>
</tr>
<tr class="odd">
<td id="T_01141_row2_col0" class="data row2 col0">Age squared</td>
<td id="T_01141_row2_col1" class="data row2 col1">-0.0030</td>
<td id="T_01141_row2_col2" class="data row2 col2">-0.0030</td>
<td id="T_01141_row2_col3" class="data row2 col3">0.0003</td>
<td id="T_01141_row2_col4" class="data row2 col4">0.0003</td>
</tr>
<tr class="even">
<td id="T_01141_row3_col0" class="data row3 col0">Region_Northeast</td>
<td id="T_01141_row3_col1" class="data row3 col1">0.0292</td>
<td id="T_01141_row3_col2" class="data row3 col2">0.0292</td>
<td id="T_01141_row3_col3" class="data row3 col3">0.0436</td>
<td id="T_01141_row3_col4" class="data row3 col4">0.0436</td>
</tr>
<tr class="odd">
<td id="T_01141_row4_col0" class="data row4 col0">Region_Northwest</td>
<td id="T_01141_row4_col1" class="data row4 col1">-0.0176</td>
<td id="T_01141_row4_col2" class="data row4 col2">-0.0176</td>
<td id="T_01141_row4_col3" class="data row4 col3">0.0538</td>
<td id="T_01141_row4_col4" class="data row4 col4">0.0538</td>
</tr>
<tr class="even">
<td id="T_01141_row5_col0" class="data row5 col0">Region_South</td>
<td id="T_01141_row5_col1" class="data row5 col1">0.0566</td>
<td id="T_01141_row5_col2" class="data row5 col2">0.0566</td>
<td id="T_01141_row5_col3" class="data row5 col3">0.0527</td>
<td id="T_01141_row5_col4" class="data row5 col4">0.0527</td>
</tr>
<tr class="odd">
<td id="T_01141_row6_col0" class="data row6 col0">Region_Southwest</td>
<td id="T_01141_row6_col1" class="data row6 col1">0.0506</td>
<td id="T_01141_row6_col2" class="data row6 col2">0.0506</td>
<td id="T_01141_row6_col3" class="data row6 col3">0.0472</td>
<td id="T_01141_row6_col4" class="data row6 col4">0.0472</td>
</tr>
<tr class="even">
<td id="T_01141_row7_col0" class="data row7 col0">Blueprinty customer</td>
<td id="T_01141_row7_col1" class="data row7 col1">0.2076</td>
<td id="T_01141_row7_col2" class="data row7 col2">0.2076</td>
<td id="T_01141_row7_col3" class="data row7 col3">0.0309</td>
<td id="T_01141_row7_col4" class="data row7 col4">0.0309</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p>The custom maximum likelihood estimates match the <code>statsmodels</code> Poisson GLM estimates almost exactly. This is reassuring because both approaches are estimating the same likelihood. Since the custom model uses the analytical Hessian of the negative log-likelihood, the standard errors also line up closely with the GLM output.</p>
<p>The customer coefficient is positive, which means that Blueprinty customers are predicted to have higher patent counts than otherwise similar non-customers, after controlling for firm age, age squared, and region. The estimated customer coefficient is about 0.208. Because the Poisson model uses a log link, exponentiating this coefficient gives an incidence rate ratio:</p>
<p><span class="math display">\[
\exp(0.208) \approx 1.231
\]</span></p>
<p>This means that, holding firm age and region constant, Blueprinty customers are predicted to have about 23.1% more patents than comparable non-customers.</p>
<p>The age coefficients also make sense. The coefficient on age is positive, while the coefficient on age squared is negative. This suggests that expected patent counts increase as firms get older, but the increase slows down at higher ages. In other words, the relationship between firm age and patenting appears to be concave rather than perfectly linear.</p>
<p>The region coefficients are measured relative to the omitted Midwest category. Their signs indicate whether firms in those regions are predicted to have higher or lower patent counts than similar Midwest firms. In this model, the regional effects are relatively small compared with the customer effect.</p>
<p>Overall, the regression results support Blueprinty’s claim in a controlled descriptive sense: customers are associated with higher expected patent counts even after accounting for observable differences in age and region. However, because customer status was not randomly assigned, this estimate should still be interpreted as an association rather than definitive causal proof.</p>
</div>
</div>
</div>
</div>
</section>
<section id="the-effect-of-blueprintys-software" class="level2">
<h2 class="anchored" data-anchor-id="the-effect-of-blueprintys-software">The Effect of Blueprinty’s Software</h2>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The coefficient on <code>Blueprinty customer</code> tells us the multiplicative effect of being a customer on the expected patent count, holding age and region fixed. However, that coefficient is still measured on the log scale. To make the result easier to interpret, I construct two counterfactual datasets.</p>
<p>The first counterfactual dataset, <span class="math inline">\(X_0\)</span>, treats every firm as if it were not a Blueprinty customer. The second counterfactual dataset, <span class="math inline">\(X_1\)</span>, treats every firm as if it were a Blueprinty customer. Importantly, each firm’s age and region are held fixed at their observed values. The only thing that changes is customer status.</p>
<p>Using the fitted Poisson regression model, I predict the expected number of patents for every firm under both scenarios:</p>
<p><span class="math display">\[
\hat{Y}_{i0} = \exp(X_{i0}'\hat{\beta})
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\hat{Y}_{i1} = \exp(X_{i1}'\hat{\beta})
\]</span></p>
<p>The estimated average effect of Blueprinty’s software is then:</p>
<p><span class="math display">\[
\frac{1}{n}
\sum_{i=1}^{n}
\left(
\hat{Y}_{i1} - \hat{Y}_{i0}
\right)
\]</span></p>
<p>This quantity answers the question: holding each firm’s age and region fixed, how many additional patents would we expect if every firm used Blueprinty’s software?</p>
<div id="b87bcd0d" class="cell" data-execution_count="17">
<div class="cell-output cell-output-display">
<style type="text/css">
</style>

<div id="T_db9ce" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_db9ce-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Counterfactual Predicted Patent Counts
</figcaption>
<div aria-describedby="T_db9ce-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_db9ce" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_db9ce_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Scenario</th>
<th id="T_db9ce_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Average predicted patents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_db9ce_row0_col0" class="data row0 col0">If no firms were Blueprinty customers</td>
<td id="T_db9ce_row0_col1" class="data row0 col1">3.436</td>
</tr>
<tr class="even">
<td id="T_db9ce_row1_col0" class="data row1 col0">If all firms were Blueprinty customers</td>
<td id="T_db9ce_row1_col1" class="data row1 col1">4.229</td>
</tr>
<tr class="odd">
<td id="T_db9ce_row2_col0" class="data row2 col0">Estimated average effect</td>
<td id="T_db9ce_row2_col1" class="data row2 col1">0.793</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p>The model predicts that if no firms were Blueprinty customers, the average expected number of patents would be about 3.436 over the five-year period. If all firms were Blueprinty customers, the average expected number of patents would be about 4.229. The difference between these two counterfactual predictions is about 0.793 patents per firm.</p>
<div id="b6a616f2" class="cell" data-fig-height="3.5" data-fig-width="6" data-execution_count="18">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-19-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="714" height="415"></p>
</figure>
</div>
</div>
</div>
<p>The estimated effect can also be expressed as a percentage increase:</p>
<p><span class="math display">\[
\frac{4.229 - 3.436}{3.436}
\approx 0.231
\]</span></p>
<p>So the model predicts that Blueprinty customers have about 23.1% more patents than comparable non-customers, holding firm age and region fixed.</p>
<p>In practical terms, the estimated average effect is:</p>
<p><span class="math display">\[
4.229 - 3.436 = 0.793
\]</span></p>
<p>This means that Blueprinty’s software is associated with approximately 0.79 additional patents per firm over a five-year period. For a single firm, this may sound modest. However, across many engineering firms, an effect of this size could translate into a meaningful increase in total patent approvals.</p>
<p>Overall, this analysis provides evidence consistent with Blueprinty’s marketing claim: firms using Blueprinty’s software are predicted to receive more patents than similar firms that do not use the software. However, the result should still be interpreted carefully. This is an observational study, not a randomized experiment. The model controls for observed differences in firm age and region, but it cannot rule out unobserved differences between customers and non-customers. For example, Blueprinty customers may have been more innovative, better funded, or more aggressive about patenting even before using the software.</p>
<p>Therefore, the analysis supports a positive association between Blueprinty usage and patent output, but it does not prove with certainty that the software itself causes firms to receive more patents.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>