<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lawrence Lin">
<meta name="dcterms.date" content="2026-05-27">

<title>MaxDiff Analysis of MSBA Class Preferences – Lawrence Lin</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-89ba6b723c0026cab07b5b492f14f291.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Lawrence Lin</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Experience.html"> 
<span class="menu-text">Experience</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a></li>
  <li><a href="#counts-analysis" id="toc-counts-analysis" class="nav-link" data-scroll-target="#counts-analysis">Counts Analysis</a></li>
  <li><a href="#from-maxdiff-data-to-mnl-choices" id="toc-from-maxdiff-data-to-mnl-choices" class="nav-link" data-scroll-target="#from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</a></li>
  <li><a href="#mnl-via-maximum-likelihood" id="toc-mnl-via-maximum-likelihood" class="nav-link" data-scroll-target="#mnl-via-maximum-likelihood">MNL via Maximum Likelihood</a></li>
  <li><a href="#mnl-via-bayesian-estimation" id="toc-mnl-via-bayesian-estimation" class="nav-link" data-scroll-target="#mnl-via-bayesian-estimation">MNL via Bayesian Estimation</a></li>
  <li><a href="#comparing-the-three-methods" id="toc-comparing-the-three-methods" class="nav-link" data-scroll-target="#comparing-the-three-methods">Comparing the Three Methods</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MaxDiff Analysis of MSBA Class Preferences</h1>
<p class="subtitle lead">Counts, MLE, and Bayesian estimation of the MNL model</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lawrence Lin </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 27, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>MaxDiff, also called Best-Worst Scaling, is a survey method for measuring relative preferences. Instead of asking respondents to rate each item on a numeric scale, the survey repeatedly shows a small set of items and asks for two choices: the most-preferred item and the least-preferred item. In this survey, each valid MaxDiff screen shows 4 MSBA classes.</p>
<p>MaxDiff is useful because people are generally better at making trade-offs than at calibrating rating scales. For example, two students may both give several classes a 7 out of 10, but those 7s may not mean the same thing. A best-worst task forces differentiation: when four classes appear together, the respondent must decide which one is strongest and which one is weakest. This reduces scale-use bias and gives us information about preference ordering.</p>
<p>In this assignment, the items are 10 core MSBA classes at UCSD Rady. I estimate relative preference using three approaches. First, I compute a simple counts score: the percentage of times each class is chosen best minus the percentage of times it is chosen worst. Second, I estimate a multinomial logit (MNL) model by maximum likelihood. Third, I estimate the same MNL model using a Bayesian random-walk Metropolis-Hastings sampler.</p>
<p>I expect the three methods to agree on the broad story, especially at the top and bottom of the ranking. They should differ most in the middle, where classes have similar preference strength and small changes in estimation method can flip the order. The MNL and Bayesian methods also give a more formal way to quantify uncertainty than the simple counts score.</p>
</div>
</div>
</div>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<div class="callout-">
<p>The data file is organized at the item-task level: each row is one class shown to one respondent on one MaxDiff screen. I first read the response file and the item-label file, then standardize the column names. One important cleaning step is needed: the raw file contains both 4-item MaxDiff tasks and later 2-item choice tasks. Since this assignment is about MaxDiff, I keep only tasks that have exactly four rows, one best choice, one worst choice, and two unchosen items.</p>
<div id="data-read-clean-check" class="cell" data-execution_count="1">
<div id="data-read-clean-check-1" class="cell-output cell-output-display cell-output-markdown">
<section id="item-labels" class="level3">
<h3 class="anchored" data-anchor-id="item-labels">Item labels</h3>
</section>
</div>
<div id="data-read-clean-check-2" class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">item</th>
<th data-quarto-table-cell-role="th">item_label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Peterson)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The table below checks the raw task structure before filtering. A valid MaxDiff task should have 4 rows, exactly one <code>Response = 1</code>, exactly one <code>Response = -1</code>, and two rows with <code>Response = 0</code>.</p>
<div id="raw-task-structure" class="cell" data-execution_count="2">
<div id="raw-task-structure-1" class="cell-output cell-output-display cell-output-markdown">
<section id="raw-task-pattern-check" class="level3">
<h3 class="anchored" data-anchor-id="raw-task-pattern-check">Raw task pattern check</h3>
</section>
</div>
<div id="raw-task-structure-2" class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">n_rows</th>
<th data-quarto-table-cell-role="th">n_best</th>
<th data-quarto-table-cell-role="th">n_worst</th>
<th data-quarto-table-cell-role="th">n_zero</th>
<th data-quarto-table-cell-role="th">all_items_labeled</th>
<th data-quarto-table-cell-role="th">valid_maxdiff_task</th>
<th data-quarto-table-cell-role="th">n_tasks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1</th>
<td>4</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>True</td>
<td>True</td>
<td>680</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">0</th>
<td>2</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>False</td>
<td>False</td>
<td>595</td>
</tr>
</tbody>
</table>

</div>
</div>
<div id="raw-task-structure-3" class="cell-output cell-output-display cell-output-markdown">
<p>The raw data contain <strong>3,910 rows</strong> across <strong>1,275 respondent-task combinations</strong>. After keeping only valid 4-item MaxDiff tasks, the analysis data contain <strong>2,720 rows</strong> from <strong>680 MaxDiff tasks</strong>. The remaining <strong>595 tasks</strong> are dropped because they are not 4-item MaxDiff tasks.</p>
</div>
</div>
<p>Next, I report the basic descriptives: the number of respondents, tasks per respondent, items per task, total items in the study, and total valid MaxDiff tasks.</p>
<div id="cell-basic-descriptives" class="cell" data-execution_count="3">
<div id="basic-descriptives" class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">metric</th>
<th data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Respondents (N)</td>
<td>85</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Tasks per respondent (T)</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Items per task (J)</td>
<td>4</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Total study items</td>
<td>10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Valid MaxDiff tasks</td>
<td>680</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Valid MaxDiff rows</td>
<td>2720</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The cleaned data pass the MaxDiff sanity check: every task has exactly one best choice, exactly one worst choice, and two unchosen alternatives.</p>
<div id="cell-sanity-check-cleaned-data" class="cell" data-execution_count="4">
<div id="sanity-check-cleaned-data" class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">passes_check</th>
<th data-quarto-table-cell-role="th">n_tasks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>True</td>
<td>680</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Finally, I report how often each item was shown. The exposure counts are similar across the 10 classes, which is what we expect from a balanced MaxDiff design.</p>
<div id="item-exposure" class="cell" data-execution_count="5">
<div id="item-exposure-1" class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">item</th>
<th data-quarto-table-cell-role="th">item_label</th>
<th data-quarto-table-cell-role="th">times_shown</th>
<th data-quarto-table-cell-role="th">times_best</th>
<th data-quarto-table-cell-role="th">times_worst</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td>273</td>
<td>33</td>
<td>90</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>274</td>
<td>55</td>
<td>56</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td>272</td>
<td>43</td>
<td>101</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>276</td>
<td>77</td>
<td>60</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>270</td>
<td>93</td>
<td>55</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td>267</td>
<td>33</td>
<td>111</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>276</td>
<td>104</td>
<td>71</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>272</td>
<td>72</td>
<td>69</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td>274</td>
<td>147</td>
<td>12</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td>266</td>
<td>23</td>
<td>55</td>
</tr>
</tbody>
</table>

</div>
</div>
<div id="item-exposure-2" class="cell-output cell-output-display cell-output-markdown">
<p>Each class was shown between <strong>266</strong> and <strong>276</strong> times, so exposure is roughly balanced across the 10 items.</p>
</div>
</div>
</div>
</section>
<section id="counts-analysis" class="level2">
<h2 class="anchored" data-anchor-id="counts-analysis">Counts Analysis</h2>
<div class="callout-">
<p>The first method is a simple counts analysis. For each class, I calculate how often it was selected as the most-preferred class when it appeared, and how often it was selected as the least-preferred class when it appeared. The counts score is the difference between these two percentages:</p>
<p><span class="math display">\[
\text{score}_j = \%\text{best}_j - \%\text{worst}_j
\]</span></p>
<p>A score close to +1 means that a class is almost always chosen as the best option when shown. A score close to -1 means that it is almost always chosen as the worst option when shown. A score near 0 means that the class is either middle-of-the-pack or receives mixed reactions from respondents.</p>
<div id="cell-counts-analysis-table" class="cell" data-message="false" data-execution_count="6">
<div id="counts-analysis-table" class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Rank</th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Times shown</th>
<th data-quarto-table-cell-role="th">Times best</th>
<th data-quarto-table-cell-role="th">Times worst</th>
<th data-quarto-table-cell-role="th">% best</th>
<th data-quarto-table-cell-role="th">% worst</th>
<th data-quarto-table-cell-role="th">Counts score</th>
<th data-quarto-table-cell-role="th">95% CI lower</th>
<th data-quarto-table-cell-role="th">95% CI upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td>274</td>
<td>147</td>
<td>12</td>
<td>53.6%</td>
<td>4.4%</td>
<td>0.493</td>
<td>0.401</td>
<td>0.582</td>
</tr>
<tr class="even">
<td>2</td>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>270</td>
<td>93</td>
<td>55</td>
<td>34.4%</td>
<td>20.4%</td>
<td>0.141</td>
<td>0.018</td>
<td>0.264</td>
</tr>
<tr class="odd">
<td>3</td>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>276</td>
<td>104</td>
<td>71</td>
<td>37.7%</td>
<td>25.7%</td>
<td>0.120</td>
<td>-0.032</td>
<td>0.260</td>
</tr>
<tr class="even">
<td>4</td>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>276</td>
<td>77</td>
<td>60</td>
<td>27.9%</td>
<td>21.7%</td>
<td>0.062</td>
<td>-0.051</td>
<td>0.180</td>
</tr>
<tr class="odd">
<td>5</td>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>272</td>
<td>72</td>
<td>69</td>
<td>26.5%</td>
<td>25.4%</td>
<td>0.011</td>
<td>-0.114</td>
<td>0.133</td>
</tr>
<tr class="even">
<td>6</td>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>274</td>
<td>55</td>
<td>56</td>
<td>20.1%</td>
<td>20.4%</td>
<td>-0.004</td>
<td>-0.111</td>
<td>0.107</td>
</tr>
<tr class="odd">
<td>7</td>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td>266</td>
<td>23</td>
<td>55</td>
<td>8.6%</td>
<td>20.7%</td>
<td>-0.120</td>
<td>-0.202</td>
<td>-0.041</td>
</tr>
<tr class="even">
<td>8</td>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td>273</td>
<td>33</td>
<td>90</td>
<td>12.1%</td>
<td>33.0%</td>
<td>-0.209</td>
<td>-0.302</td>
<td>-0.105</td>
</tr>
<tr class="odd">
<td>9</td>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td>272</td>
<td>43</td>
<td>101</td>
<td>15.8%</td>
<td>37.1%</td>
<td>-0.213</td>
<td>-0.328</td>
<td>-0.102</td>
</tr>
<tr class="even">
<td>10</td>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td>267</td>
<td>33</td>
<td>111</td>
<td>12.4%</td>
<td>41.6%</td>
<td>-0.292</td>
<td>-0.397</td>
<td>-0.189</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The ranked table shows a clear spread in student preferences. Classes with positive scores were selected as best more often than worst, while classes with negative scores were selected as worst more often than best.</p>
<div id="cell-counts-analysis-plot" class="cell" data-fig-height="6" data-fig-width="10" data-message="false" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/counts-analysis-plot-output-1.png" id="counts-analysis-plot" width="950" height="564" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-counts-analysis-written-summary" class="cell" data-message="false" data-execution_count="8">
<div id="counts-analysis-written-summary" class="cell-output cell-output-display cell-output-markdown">
<p>The most preferred class by the simple counts score is <strong>MGTA 495 Marketing Analytics (Spring with Yavorsky)</strong>, with a score of <strong>0.493</strong>. The top three classes are <strong>MGTA 495 Marketing Analytics (Spring with Yavorsky) (0.493), MGTA 453 Business Analytics (Fall with August) (0.141), MGTA 455 Customer Analytics (Winter with Nijs) (0.120)</strong>. At the bottom of the ranking, the least preferred class is <strong>MGTA 444 Analytics Consulting (Winter with Peterson)</strong>, with a score of <strong>-0.292</strong>. The three lowest-ranked classes are <strong>MGTA 444 Analytics Consulting (Winter with Peterson) (-0.292), MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin) (-0.213), MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs) (-0.209)</strong>. Overall, the counts analysis gives a simple and intuitive first look at the data: some classes are clearly preferred, some are clearly less preferred, and the middle group is closer together.</p>
</div>
</div>
</div>
</section>
<section id="from-maxdiff-data-to-mnl-choices" class="level2">
<h2 class="anchored" data-anchor-id="from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</h2>
<div class="callout-">
<p>The MaxDiff responses can be treated as multinomial logit choice data. In each task, a respondent sees four classes and makes two choices. First, they choose the class they like the most from the full set of four. Then, after the best class is removed, they choose the class they like the least from the remaining three.</p>
<p>For the best-choice part, the MNL model assigns each item <span class="math inline">\(j\)</span> a utility coefficient <span class="math inline">\(\beta_j\)</span>. If the task shows items <span class="math inline">\(\{a,b,c,d\}\)</span>, the probability that item <span class="math inline">\(b\)</span> is chosen as best is:</p>
<p><span class="math display">\[
P(\text{best}=b)
=
\frac{\exp(\beta_b)}
{\exp(\beta_a)+\exp(\beta_b)+\exp(\beta_c)+\exp(\beta_d)}
\]</span></p>
<p>For the worst-choice part, I use the same utilities but flip the sign. Intuitively, an item with high positive utility should be unlikely to be selected as worst, while an item with low utility should be more likely to be selected as worst. If item <span class="math inline">\(b\)</span> was already selected as best, then the probability that item <span class="math inline">\(c\)</span> is selected as worst from the remaining items is:</p>
<p><span class="math display">\[
P(\text{worst}=c \mid \text{best}=b)
=
\frac{\exp(-\beta_c)}
{\exp(-\beta_a)+\exp(-\beta_c)+\exp(-\beta_d)}
\]</span></p>
<p>Therefore, each MaxDiff task contributes two MNL choice observations: one best-choice observation from four alternatives, and one worst-choice observation from the remaining three alternatives.</p>
<p>The model also needs a normalization for identification. Adding the same constant to every <span class="math inline">\(\beta_j\)</span> would not change any of the MNL probabilities, so the absolute level of utility is not identified. I set <span class="math inline">\(\beta_1 = 0\)</span> and estimate the remaining nine coefficients, <span class="math inline">\(\beta_2,\ldots,\beta_{10}\)</span>, relative to item 1.</p>
<div id="reshape-maxdiff-to-mnl" class="cell" data-message="false" data-execution_count="9">
<div id="reshape-maxdiff-to-mnl-1" class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Choice observation</th>
<th data-quarto-table-cell-role="th">Number of observations</th>
<th data-quarto-table-cell-role="th">Minimum alternatives</th>
<th data-quarto-table-cell-role="th">Maximum alternatives</th>
<th data-quarto-table-cell-role="th">Chosen alternatives per observation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Best choice</td>
<td>680</td>
<td>4</td>
<td>4</td>
<td>1.0</td>
</tr>
<tr class="even">
<td>Worst choice</td>
<td>680</td>
<td>3</td>
<td>3</td>
<td>1.0</td>
</tr>
</tbody>
</table>
</div>
<div id="reshape-maxdiff-to-mnl-2" class="cell-output cell-output-display cell-output-markdown">
<p>After reshaping, the <strong>680 valid MaxDiff tasks</strong> become <strong>1,360 MNL choice observations</strong>: one best-choice observation and one worst-choice observation for each task. This task-level structure will be used in the likelihood function in the next section.</p>
</div>
</div>
</div>
</section>
<section id="mnl-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-maximum-likelihood">MNL via Maximum Likelihood</h2>
<div class="callout-">
<p>Next, I estimate the MNL model by maximum likelihood. Each item has a utility coefficient <span class="math inline">\(\beta_j\)</span>, with item 1 used as the reference category. Therefore, I set <span class="math inline">\(\beta_1 = 0\)</span> and estimate the remaining nine coefficients.</p>
<p>For each MaxDiff task, the log-likelihood combines the probability of the best choice and the probability of the worst choice. The log-likelihood is:</p>
<p><span class="math display">\[
\ell(\boldsymbol{\beta})
=
\sum_{\text{tasks}}
\left[
\beta_{j_b^*}
-
\log \sum_{j \in \text{shown}} \exp(\beta_j)
-
\beta_{j_w^*}
-
\log \sum_{j \in \text{shown} \setminus \{j_b^*\}} \exp(-\beta_j)
\right]
\]</span></p>
<p>where <span class="math inline">\(j_b^*\)</span> is the item chosen as best and <span class="math inline">\(j_w^*\)</span> is the item chosen as worst. I maximize this log-likelihood using BFGS. For interpretation, I also convert the utility estimates into shares of preference:</p>
<p><span class="math display">\[
\hat{s}_j
=
\frac{\exp(\hat{\beta}_j)}
{\sum_{k=1}^{10} \exp(\hat{\beta}_k)}
\]</span></p>
<p>These shares can be interpreted as the model-implied probability that each class would be chosen if all 10 classes appeared together on one screen.</p>
<div id="mle-standard-errors" class="cell" data-message="false" data-execution_count="11">
<div id="mle-standard-errors-1" class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">MLE rank</th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Beta hat</th>
<th data-quarto-table-cell-role="th">SE</th>
<th data-quarto-table-cell-role="th">Share of preference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td>1.630</td>
<td>0.146</td>
<td>28.4%</td>
</tr>
<tr class="even">
<td>2</td>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.744</td>
<td>0.142</td>
<td>11.7%</td>
</tr>
<tr class="odd">
<td>3</td>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.656</td>
<td>0.142</td>
<td>10.7%</td>
</tr>
<tr class="even">
<td>4</td>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.555</td>
<td>0.140</td>
<td>9.7%</td>
</tr>
<tr class="odd">
<td>5</td>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.443</td>
<td>0.140</td>
<td>8.7%</td>
</tr>
<tr class="even">
<td>6</td>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.438</td>
<td>0.137</td>
<td>8.6%</td>
</tr>
<tr class="odd">
<td>7</td>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td>0.236</td>
<td>0.137</td>
<td>7.0%</td>
</tr>
<tr class="even">
<td>8</td>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td>0.000</td>
<td>Reference</td>
<td>5.6%</td>
</tr>
<tr class="odd">
<td>9</td>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td>-0.067</td>
<td>0.139</td>
<td>5.2%</td>
</tr>
<tr class="even">
<td>10</td>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td>-0.239</td>
<td>0.141</td>
<td>4.4%</td>
</tr>
</tbody>
</table>
</div>
<div id="mle-standard-errors-2" class="cell-output cell-output-display cell-output-markdown">
<p>The MNL model converged successfully. The maximized log-likelihood is <strong>-1572.73</strong>.</p>
</div>
</div>
<p>The table reports the estimated MNL utilities, standard errors, and model-implied shares of preference. Since <span class="math inline">\(\beta_1\)</span> is fixed to zero, all other utility coefficients are interpreted relative to item 1.</p>
<div id="cell-mle-share-plot" class="cell" data-fig-height="6" data-fig-width="10" data-message="false" data-execution_count="12">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/mle-share-plot-output-1.png" id="mle-share-plot" width="950" height="564" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="mle-vs-counts-comparison" class="cell" data-message="false" data-execution_count="13">
<div id="mle-vs-counts-comparison-1" class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Counts score</th>
<th data-quarto-table-cell-role="th">Counts rank</th>
<th data-quarto-table-cell-role="th">MLE share</th>
<th data-quarto-table-cell-role="th">MLE rank</th>
<th data-quarto-table-cell-role="th">Counts rank minus MLE rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td>0.493</td>
<td>1</td>
<td>28.4%</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.141</td>
<td>2</td>
<td>11.7%</td>
<td>2</td>
<td>0</td>
</tr>
<tr class="odd">
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.120</td>
<td>3</td>
<td>10.7%</td>
<td>3</td>
<td>0</td>
</tr>
<tr class="even">
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.062</td>
<td>4</td>
<td>9.7%</td>
<td>4</td>
<td>0</td>
</tr>
<tr class="odd">
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.011</td>
<td>5</td>
<td>8.7%</td>
<td>5</td>
<td>0</td>
</tr>
<tr class="even">
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>-0.004</td>
<td>6</td>
<td>8.6%</td>
<td>6</td>
<td>0</td>
</tr>
<tr class="odd">
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td>-0.120</td>
<td>7</td>
<td>7.0%</td>
<td>7</td>
<td>0</td>
</tr>
<tr class="even">
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td>-0.209</td>
<td>8</td>
<td>5.6%</td>
<td>8</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td>-0.213</td>
<td>9</td>
<td>5.2%</td>
<td>9</td>
<td>0</td>
</tr>
<tr class="even">
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td>-0.292</td>
<td>10</td>
<td>4.4%</td>
<td>10</td>
<td>0</td>
</tr>
</tbody>
</table>
</div>
<div id="mle-vs-counts-comparison-2" class="cell-output cell-output-display cell-output-markdown">
<p>The MLE ranking is identical to the simple counts ranking. This is not too surprising because the MaxDiff design is fairly balanced, so the counts score already captures much of the preference ordering. The MNL model adds a formal choice model and converts the ranking into interpretable preference shares. The highest MLE share belongs to <strong>MGTA 495 Marketing Analytics (Spring with Yavorsky)</strong> with a share of <strong>28.4%</strong>. The lowest MLE share belongs to <strong>MGTA 444 Analytics Consulting (Winter with Peterson)</strong> with a share of <strong>4.4%</strong>.</p>
</div>
</div>
</div>
</section>
<section id="mnl-via-bayesian-estimation" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-bayesian-estimation">MNL via Bayesian Estimation</h2>
<div class="callout-">
<p>I next estimate the same MNL model using Bayesian methods. The Bayesian model combines the likelihood from the previous section with a prior distribution over the utility coefficients. The posterior distribution is:</p>
<p><span class="math display">\[
\pi(\boldsymbol{\beta} \mid \boldsymbol{y})
\propto
L(\boldsymbol{\beta}) \cdot \pi(\boldsymbol{\beta})
\]</span></p>
<p>I use a weakly informative normal prior on the nine free coefficients:</p>
<p><span class="math display">\[
\beta_2, \ldots, \beta_{10} \sim N(0, 10)
\]</span></p>
<p>The prior standard deviation is <span class="math inline">\(\sqrt{10} \approx 3.16\)</span>, which is fairly wide on the logit utility scale. As before, item 1 is the reference item, so <span class="math inline">\(\beta_1 = 0\)</span>. I sample from the posterior using a random-walk Metropolis-Hastings algorithm.</p>
<p>I first tune the proposal step size with short pilot chains. The goal is an acceptance rate around 25% to 40%, which usually gives a reasonable balance between moving too slowly and rejecting too many proposals.</p>
<div id="bayes-tuning" class="cell" data-message="false" data-execution_count="15">
<div id="bayes-tuning-1" class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Step size</th>
<th data-quarto-table-cell-role="th">Pilot acceptance rate</th>
<th data-quarto-table-cell-role="th">Distance from 30%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.04</td>
<td>0.582</td>
<td>0.282</td>
</tr>
<tr class="even">
<td>0.06</td>
<td>0.396</td>
<td>0.096</td>
</tr>
<tr class="odd">
<td>0.08</td>
<td>0.292</td>
<td>0.009</td>
</tr>
<tr class="even">
<td>0.10</td>
<td>0.198</td>
<td>0.101</td>
</tr>
<tr class="odd">
<td>0.12</td>
<td>0.124</td>
<td>0.176</td>
</tr>
</tbody>
</table>
</div>
<div id="bayes-tuning-2" class="cell-output cell-output-display cell-output-markdown">
<p>Based on the pilot chains, I use a final proposal step size of <strong>0.08</strong>.</p>
</div>
</div>
<p>Using the tuned step size, I run the final Metropolis-Hastings chain for 20,000 iterations and discard the first 25% as burn-in.</p>
<div id="cell-run-bayes-mcmc" class="cell" data-message="false" data-execution_count="16">
<div id="run-bayes-mcmc" class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Quantity</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Iterations</td>
<td>20,000</td>
</tr>
<tr class="even">
<td>Burn-in draws</td>
<td>5,000</td>
</tr>
<tr class="odd">
<td>Post-burn-in draws</td>
<td>15,000</td>
</tr>
<tr class="even">
<td>Proposal step size</td>
<td>0.08</td>
</tr>
<tr class="odd">
<td>Final acceptance rate</td>
<td>0.283</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The trace plots below show representative posterior draws for three utility coefficients. A good trace plot should look like a stable “fuzzy caterpillar,” meaning that the chain moves around a stable region rather than drifting upward or downward over time.</p>
<div id="cell-bayes-trace-plots" class="cell" data-fig-height="7" data-fig-width="10" data-message="false" data-execution_count="17">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/bayes-trace-plots-output-1.png" id="bayes-trace-plots" width="939" height="660" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>After burn-in, I summarize the posterior draws. For each draw, I convert the utility coefficients into shares of preference using the softmax transformation. This allows me to report both posterior mean shares and 95% credible intervals for the shares.</p>
<div id="cell-bayes-posterior-summary" class="cell" data-message="false" data-execution_count="18">
<div id="bayes-posterior-summary" class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Bayes rank</th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Posterior mean beta</th>
<th data-quarto-table-cell-role="th">95% beta credible interval</th>
<th data-quarto-table-cell-role="th">Posterior mean share</th>
<th data-quarto-table-cell-role="th">95% share credible interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td>1.599</td>
<td>[1.325, 1.883]</td>
<td>28.2%</td>
<td>[24.1%, 33.0%]</td>
</tr>
<tr class="even">
<td>2</td>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.723</td>
<td>[0.463, 0.988]</td>
<td>11.7%</td>
<td>[9.7%, 13.9%]</td>
</tr>
<tr class="odd">
<td>3</td>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.638</td>
<td>[0.354, 0.916]</td>
<td>10.8%</td>
<td>[8.7%, 13.0%]</td>
</tr>
<tr class="even">
<td>4</td>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.525</td>
<td>[0.256, 0.799]</td>
<td>9.6%</td>
<td>[7.8%, 11.5%]</td>
</tr>
<tr class="odd">
<td>5</td>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.417</td>
<td>[0.147, 0.682]</td>
<td>8.7%</td>
<td>[7.1%, 10.4%]</td>
</tr>
<tr class="even">
<td>6</td>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.411</td>
<td>[0.144, 0.676]</td>
<td>8.6%</td>
<td>[7.1%, 10.3%]</td>
</tr>
<tr class="odd">
<td>7</td>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td>0.216</td>
<td>[-0.038, 0.473]</td>
<td>7.1%</td>
<td>[5.9%, 8.5%]</td>
</tr>
<tr class="even">
<td>8</td>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td>0.000</td>
<td>[0.0, 0.0]</td>
<td>5.7%</td>
<td>[4.7%, 6.8%]</td>
</tr>
<tr class="odd">
<td>9</td>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td>-0.089</td>
<td>[-0.372, 0.174]</td>
<td>5.2%</td>
<td>[4.2%, 6.4%]</td>
</tr>
<tr class="even">
<td>10</td>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td>-0.271</td>
<td>[-0.556, -0.006]</td>
<td>4.4%</td>
<td>[3.5%, 5.3%]</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="cell-bayes-share-plot" class="cell" data-fig-height="6" data-fig-width="10" data-message="false" data-execution_count="19">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/bayes-share-plot-output-1.png" id="bayes-share-plot" width="950" height="564" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The Bayesian estimates are directly comparable to the maximum likelihood estimates. Because the prior is weak and the dataset is reasonably informative, the posterior means should be close to the MLE estimates. The main advantage of the Bayesian approach is that uncertainty for derived quantities, such as shares of preference, is easy to calculate by transforming every posterior draw.</p>
<div id="bayes-vs-mle-comparison" class="cell" data-message="false" data-execution_count="20">
<div id="bayes-vs-mle-comparison-1" class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">MLE beta</th>
<th data-quarto-table-cell-role="th">MLE SE</th>
<th data-quarto-table-cell-role="th">Bayes mean beta</th>
<th data-quarto-table-cell-role="th">Bayes posterior SD</th>
<th data-quarto-table-cell-role="th">MLE share</th>
<th data-quarto-table-cell-role="th">Bayes mean share</th>
<th data-quarto-table-cell-role="th">MLE rank</th>
<th data-quarto-table-cell-role="th">Bayes rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td>1.630</td>
<td>0.146</td>
<td>1.599</td>
<td>0.146</td>
<td>28.4%</td>
<td>28.2%</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.744</td>
<td>0.142</td>
<td>0.723</td>
<td>0.137</td>
<td>11.7%</td>
<td>11.7%</td>
<td>2</td>
<td>2</td>
</tr>
<tr class="odd">
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.656</td>
<td>0.142</td>
<td>0.638</td>
<td>0.143</td>
<td>10.7%</td>
<td>10.8%</td>
<td>3</td>
<td>3</td>
</tr>
<tr class="even">
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.555</td>
<td>0.140</td>
<td>0.525</td>
<td>0.140</td>
<td>9.7%</td>
<td>9.6%</td>
<td>4</td>
<td>4</td>
</tr>
<tr class="odd">
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.443</td>
<td>0.140</td>
<td>0.411</td>
<td>0.137</td>
<td>8.7%</td>
<td>8.6%</td>
<td>5</td>
<td>6</td>
</tr>
<tr class="even">
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.438</td>
<td>0.137</td>
<td>0.417</td>
<td>0.139</td>
<td>8.6%</td>
<td>8.7%</td>
<td>6</td>
<td>5</td>
</tr>
<tr class="odd">
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td>0.236</td>
<td>0.137</td>
<td>0.216</td>
<td>0.134</td>
<td>7.0%</td>
<td>7.1%</td>
<td>7</td>
<td>7</td>
</tr>
<tr class="even">
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td>0.000</td>
<td>Reference</td>
<td>0.000</td>
<td>Fixed</td>
<td>5.6%</td>
<td>5.7%</td>
<td>8</td>
<td>8</td>
</tr>
<tr class="odd">
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td>-0.067</td>
<td>0.139</td>
<td>-0.089</td>
<td>0.143</td>
<td>5.2%</td>
<td>5.2%</td>
<td>9</td>
<td>9</td>
</tr>
<tr class="even">
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td>-0.239</td>
<td>0.141</td>
<td>-0.271</td>
<td>0.141</td>
<td>4.4%</td>
<td>4.4%</td>
<td>10</td>
<td>10</td>
</tr>
</tbody>
</table>
</div>
<div id="bayes-vs-mle-comparison-2" class="cell-output cell-output-display cell-output-markdown">
<p>The Bayesian posterior ranking places <strong>MGTA 495 Marketing Analytics (Spring with Yavorsky)</strong> first, with a posterior mean share of <strong>28.2%</strong>. The lowest-ranked class is <strong>MGTA 444 Analytics Consulting (Winter with Peterson)</strong>, with a posterior mean share of <strong>4.4%</strong>. The MLE and Bayesian rankings are very similar, with small rank changes for MGTA 464 SQL (Summer with Nijs), MGTA 454 Capstone Project (Spring with Advisor). The largest absolute difference between an MLE beta estimate and a Bayesian posterior mean beta is for <strong>MGTA 454 Capstone Project (Spring with Advisor)</strong>, but the difference is only <strong>0.032</strong>. Overall, the Bayesian results closely match the MLE results, while also giving credible intervals for the preference shares.</p>
</div>
</div>
</div>
</section>
<section id="comparing-the-three-methods" class="level2">
<h2 class="anchored" data-anchor-id="comparing-the-three-methods">Comparing the Three Methods</h2>
<div class="callout-">
<p>The three methods give three different views of the same MaxDiff preference data. The counts analysis is the simplest descriptive summary. The MLE MNL model estimates utilities and shares of preference using an explicit choice model. The Bayesian MNL model uses the same likelihood as the MLE model, but summarizes a full posterior distribution, which makes uncertainty easier to communicate.</p>
<div id="cell-compare-three-methods-table" class="cell" data-message="false" data-execution_count="21">
<div id="compare-three-methods-table" class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Counts score</th>
<th data-quarto-table-cell-role="th">Counts rank</th>
<th data-quarto-table-cell-role="th">MLE share</th>
<th data-quarto-table-cell-role="th">MLE rank</th>
<th data-quarto-table-cell-role="th">Bayes mean share</th>
<th data-quarto-table-cell-role="th">Bayes rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td>0.493</td>
<td>1</td>
<td>28.4%</td>
<td>1</td>
<td>28.2%</td>
<td>1</td>
</tr>
<tr class="even">
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.141</td>
<td>2</td>
<td>11.7%</td>
<td>2</td>
<td>11.7%</td>
<td>2</td>
</tr>
<tr class="odd">
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.120</td>
<td>3</td>
<td>10.7%</td>
<td>3</td>
<td>10.8%</td>
<td>3</td>
</tr>
<tr class="even">
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.062</td>
<td>4</td>
<td>9.7%</td>
<td>4</td>
<td>9.6%</td>
<td>4</td>
</tr>
<tr class="odd">
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.011</td>
<td>5</td>
<td>8.7%</td>
<td>5</td>
<td>8.6%</td>
<td>6</td>
</tr>
<tr class="even">
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>-0.004</td>
<td>6</td>
<td>8.6%</td>
<td>6</td>
<td>8.7%</td>
<td>5</td>
</tr>
<tr class="odd">
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td>-0.120</td>
<td>7</td>
<td>7.0%</td>
<td>7</td>
<td>7.1%</td>
<td>7</td>
</tr>
<tr class="even">
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td>-0.209</td>
<td>8</td>
<td>5.6%</td>
<td>8</td>
<td>5.7%</td>
<td>8</td>
</tr>
<tr class="odd">
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td>-0.213</td>
<td>9</td>
<td>5.2%</td>
<td>9</td>
<td>5.2%</td>
<td>9</td>
</tr>
<tr class="even">
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td>-0.292</td>
<td>10</td>
<td>4.4%</td>
<td>10</td>
<td>4.4%</td>
<td>10</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The table is sorted by the MLE ranking. Overall, the three methods should tell a similar story, especially for the most preferred and least preferred classes. Differences are more likely to appear in the middle of the ranking, where several classes have similar preference strength.</p>
<div id="cell-compare-three-methods-plot" class="cell" data-fig-height="7" data-fig-width="18" data-message="false" data-execution_count="22">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/compare-three-methods-plot-output-1.png" id="compare-three-methods-plot" width="1718" height="661" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-compare-three-methods-written-summary" class="cell" data-message="false" data-execution_count="23">
<div id="compare-three-methods-written-summary" class="cell-output cell-output-display cell-output-markdown">
<p>All three methods agree that the top-ranked class is <strong>MGTA 495 Marketing Analytics (Spring with Yavorsky)</strong>. All three methods also agree that the lowest-ranked class is <strong>MGTA 444 Analytics Consulting (Winter with Peterson)</strong>. The largest ranking differences appear for MGTA 454 Capstone Project (Spring with Advisor) with a maximum rank gap of 1, MGTA 464 SQL (Summer with Nijs) with a maximum rank gap of 1, MGTA 453 Business Analytics (Fall with August) with a maximum rank gap of 0. These differences are mostly in the middle of the ranking, where several classes have similar estimated preference strength. The MNL model adds value over the counts analysis because it models the choice process explicitly: every item shown in a task contributes information, not only the items selected as best or worst. The Bayesian model adds a different kind of value by making uncertainty on derived quantities easy to summarize. For example, each posterior draw can be converted into a share of preference, and the distribution of those shares gives credible intervals directly.</p>
</div>
</div>
</div>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<div class="callout-">
<p>Overall, the three methods tell a consistent story about MSBA class preferences. The strongest result is that <strong>MGTA 495 Marketing Analytics</strong> is the most preferred class in the survey. It has the highest simple counts score and also receives the largest share of preference in the MNL-based models. The next strongest classes are generally <strong>MGTA 453 Business Analytics</strong> and <strong>MGTA 455 Customer Analytics</strong>, suggesting that students are especially interested in courses that connect analytics directly to business and marketing decision-making.At the other end of the ranking, <strong>MGTA 444 Analytics Consulting</strong> is the least preferred class in the counts analysis and remains near the bottom in the MNL and Bayesian results. Other lower-ranked classes include <strong>MGTA 451 Marketing/Finance/Operations</strong> and <strong>MGTA 403 AI Math, Programming, &amp; Analytics</strong>. This does not necessarily mean these classes are unimportant. Some may be more technical, more foundational, or less immediately attractive from a student-choice perspective. MaxDiff measures relative preference, not objective course value.Methodologically, the counts analysis is useful as a quick descriptive summary. It is easy to explain: for each class, we compare how often it was chosen as best versus how often it was chosen as worst. This makes counts analysis a good option for an executive dashboard or a first look at the data. However, it is less formal than the model-based approaches.The MLE MNL model is more rigorous because it models the actual choice process. Each task contributes information not only through the selected best and worst items, but also through the alternatives that were shown and not selected. The MNL results are helpful when we want formal utility estimates, standard errors, and shares of preference that can be compared across classes.The Bayesian MNL model gives very similar point estimates to the MLE model, which is reassuring. Its main advantage is uncertainty quantification. Because the Bayesian approach produces posterior draws, it is straightforward to transform every draw into shares of preference and then summarize uncertainty with credible intervals. This would be especially useful for simulations, such as predicting demand for a new class or estimating how preferences might change if the course menu changed.There are several caveats. The survey respondents are a self-selected sample of MSBA students, so the results may not generalize to all students or future cohorts. Preferences may also depend on prior coursework, career goals, current academic standing, instructor reputation, and how familiar students are with each course. In addition, the order and wording of class descriptions may affect how students interpret the choices.If I had more time, I would extend the model to estimate individual-level preferences rather than only aggregate preferences. A hierarchical Bayesian model would be useful because it could show whether different groups of students prefer different types of classes. I would also collect background information such as career interest, technical experience, and program stage to better explain why students prefer certain classes over others.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>