<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lawrence Lin">
<meta name="dcterms.date" content="2026-05-27">

<title>MaxDiff Analysis of MSBA Class Preferences – Lawrence Lin</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-89ba6b723c0026cab07b5b492f14f291.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Lawrence Lin</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Experience.html"> 
<span class="menu-text">Experience</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a></li>
  <li><a href="#the-data-1" id="toc-the-data-1" class="nav-link" data-scroll-target="#the-data-1">The Data</a></li>
  <li><a href="#counts-analysis" id="toc-counts-analysis" class="nav-link" data-scroll-target="#counts-analysis">Counts Analysis</a></li>
  <li><a href="#from-maxdiff-data-to-mnl-choices" id="toc-from-maxdiff-data-to-mnl-choices" class="nav-link" data-scroll-target="#from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</a></li>
  <li><a href="#mnl-via-maximum-likelihood" id="toc-mnl-via-maximum-likelihood" class="nav-link" data-scroll-target="#mnl-via-maximum-likelihood">MNL via Maximum Likelihood</a></li>
  <li><a href="#mnl-via-bayesian-estimation" id="toc-mnl-via-bayesian-estimation" class="nav-link" data-scroll-target="#mnl-via-bayesian-estimation">MNL via Bayesian Estimation</a></li>
  <li><a href="#comparing-the-three-methods" id="toc-comparing-the-three-methods" class="nav-link" data-scroll-target="#comparing-the-three-methods">Comparing the Three Methods</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MaxDiff Analysis of MSBA Class Preferences</h1>
<p class="subtitle lead">Counts, MLE, and Bayesian estimation of the MNL model</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lawrence Lin </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 27, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>MaxDiff, also called Best-Worst Scaling, is a survey method for measuring relative preferences. Instead of asking respondents to rate each item on a numeric scale, the survey repeatedly shows a small set of items and asks for two choices: the most-preferred item and the least-preferred item. In this survey, each valid MaxDiff screen shows 4 MSBA classes.</p>
<p>MaxDiff is useful because people are generally better at making trade-offs than at calibrating rating scales. For example, two students may both give several classes a 7 out of 10, but those 7s may not mean the same thing. A best-worst task forces differentiation: when four classes appear together, the respondent must decide which one is strongest and which one is weakest. This reduces scale-use bias and gives us information about preference ordering.</p>
<p>In this assignment, the items are 10 core MSBA classes at UCSD Rady. I estimate relative preference using three approaches. First, I compute a simple counts score: the percentage of times each class is chosen best minus the percentage of times it is chosen worst. Second, I estimate a multinomial logit (MNL) model by maximum likelihood. Third, I estimate the same MNL model using a Bayesian random-walk Metropolis-Hastings sampler.</p>
<p>I expect the three methods to agree on the broad story, especially at the top and bottom of the ranking. They should differ most in the middle, where classes have similar preference strength and small changes in estimation method can flip the order. The MNL and Bayesian methods also give a more formal way to quantify uncertainty than the simple counts score.</p>
</div>
</div>
</div>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
</section>
<section id="the-data-1" class="level2 callout-">
<h2 class="anchored" data-anchor-id="the-data-1">The Data</h2>
<p>The data file is organized at the item-task level: each row is one class shown to one respondent on one MaxDiff screen. I first read the response file and the item-label file, then standardize the column names. One important cleaning step is needed: the raw file contains both 4-item MaxDiff tasks and later 2-item choice tasks. Since this assignment is about MaxDiff, I keep only tasks that have exactly four rows, one best choice, one worst choice, and two unchosen items.</p>
<div id="data-read-clean-check" class="cell" data-execution_count="1">
<div id="data-read-clean-check-1" class="cell-output cell-output-display cell-output-markdown">
<section id="item-labels" class="level3">
<h3 class="anchored" data-anchor-id="item-labels">Item labels</h3>
</section>
</div>
<div id="data-read-clean-check-2" class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">item</th>
<th data-quarto-table-cell-role="th">item_label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Peterson)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The table below checks the raw task structure before filtering. A valid MaxDiff task should have 4 rows, exactly one <code>Response = 1</code>, exactly one <code>Response = -1</code>, and two rows with <code>Response = 0</code>.</p>
<div id="raw-task-structure" class="cell" data-execution_count="2">
<div id="raw-task-structure-1" class="cell-output cell-output-display cell-output-markdown">
<section id="raw-task-pattern-check" class="level3">
<h3 class="anchored" data-anchor-id="raw-task-pattern-check">Raw task pattern check</h3>
</section>
</div>
<div id="raw-task-structure-2" class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">n_rows</th>
<th data-quarto-table-cell-role="th">n_best</th>
<th data-quarto-table-cell-role="th">n_worst</th>
<th data-quarto-table-cell-role="th">n_zero</th>
<th data-quarto-table-cell-role="th">all_items_labeled</th>
<th data-quarto-table-cell-role="th">valid_maxdiff_task</th>
<th data-quarto-table-cell-role="th">n_tasks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1</th>
<td>4</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>True</td>
<td>True</td>
<td>680</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">0</th>
<td>2</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>False</td>
<td>False</td>
<td>595</td>
</tr>
</tbody>
</table>

</div>
</div>
<div id="raw-task-structure-3" class="cell-output cell-output-display cell-output-markdown">
<p>The raw data contain <strong>3,910 rows</strong> across <strong>1,275 respondent-task combinations</strong>. After keeping only valid 4-item MaxDiff tasks, the analysis data contain <strong>2,720 rows</strong> from <strong>680 MaxDiff tasks</strong>. The remaining <strong>595 tasks</strong> are dropped because they are not 4-item MaxDiff tasks.</p>
</div>
</div>
<p>Next, I report the basic descriptives: the number of respondents, tasks per respondent, items per task, total items in the study, and total valid MaxDiff tasks.</p>
<div id="cell-basic-descriptives" class="cell" data-execution_count="3">
<div id="basic-descriptives" class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">metric</th>
<th data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Respondents (N)</td>
<td>85</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Tasks per respondent (T)</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Items per task (J)</td>
<td>4</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Total study items</td>
<td>10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Valid MaxDiff tasks</td>
<td>680</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Valid MaxDiff rows</td>
<td>2720</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The cleaned data pass the MaxDiff sanity check: every task has exactly one best choice, exactly one worst choice, and two unchosen alternatives.</p>
<div id="cell-sanity-check-cleaned-data" class="cell" data-execution_count="4">
<div id="sanity-check-cleaned-data" class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">passes_check</th>
<th data-quarto-table-cell-role="th">n_tasks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>True</td>
<td>680</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Finally, I report how often each item was shown. The exposure counts are similar across the 10 classes, which is what we expect from a balanced MaxDiff design.</p>
<div id="item-exposure" class="cell" data-execution_count="5">
<div id="item-exposure-1" class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">item</th>
<th data-quarto-table-cell-role="th">item_label</th>
<th data-quarto-table-cell-role="th">times_shown</th>
<th data-quarto-table-cell-role="th">times_best</th>
<th data-quarto-table-cell-role="th">times_worst</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td>273</td>
<td>33</td>
<td>90</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>274</td>
<td>55</td>
<td>56</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td>272</td>
<td>43</td>
<td>101</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>276</td>
<td>77</td>
<td>60</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>270</td>
<td>93</td>
<td>55</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td>267</td>
<td>33</td>
<td>111</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>276</td>
<td>104</td>
<td>71</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>272</td>
<td>72</td>
<td>69</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td>274</td>
<td>147</td>
<td>12</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td>266</td>
<td>23</td>
<td>55</td>
</tr>
</tbody>
</table>

</div>
</div>
<div id="item-exposure-2" class="cell-output cell-output-display cell-output-markdown">
<p>Each class was shown between <strong>266</strong> and <strong>276</strong> times, so exposure is roughly balanced across the 10 items.</p>
</div>
</div>
</section>
<section id="counts-analysis" class="level2">
<h2 class="anchored" data-anchor-id="counts-analysis">Counts Analysis</h2>
<div class="callout-">
<p>The first method is a simple counts analysis. For each class, I calculate how often it was selected as the most-preferred class when it appeared, and how often it was selected as the least-preferred class when it appeared. The counts score is the difference between these two percentages:</p>
<p><span class="math display">\[
\text{score}_j = \%\text{best}_j - \%\text{worst}_j
\]</span></p>
<p>A score close to +1 means that a class is almost always chosen as the best option when shown. A score close to -1 means that it is almost always chosen as the worst option when shown. A score near 0 means that the class is either middle-of-the-pack or receives mixed reactions from respondents.</p>
<div id="cell-counts-analysis-table" class="cell" data-message="false" data-execution_count="6">
<div id="counts-analysis-table" class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Rank</th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Times shown</th>
<th data-quarto-table-cell-role="th">Times best</th>
<th data-quarto-table-cell-role="th">Times worst</th>
<th data-quarto-table-cell-role="th">% best</th>
<th data-quarto-table-cell-role="th">% worst</th>
<th data-quarto-table-cell-role="th">Counts score</th>
<th data-quarto-table-cell-role="th">95% CI lower</th>
<th data-quarto-table-cell-role="th">95% CI upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td>274</td>
<td>147</td>
<td>12</td>
<td>53.6%</td>
<td>4.4%</td>
<td>0.493</td>
<td>0.401</td>
<td>0.582</td>
</tr>
<tr class="even">
<td>2</td>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>270</td>
<td>93</td>
<td>55</td>
<td>34.4%</td>
<td>20.4%</td>
<td>0.141</td>
<td>0.018</td>
<td>0.264</td>
</tr>
<tr class="odd">
<td>3</td>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>276</td>
<td>104</td>
<td>71</td>
<td>37.7%</td>
<td>25.7%</td>
<td>0.120</td>
<td>-0.032</td>
<td>0.260</td>
</tr>
<tr class="even">
<td>4</td>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>276</td>
<td>77</td>
<td>60</td>
<td>27.9%</td>
<td>21.7%</td>
<td>0.062</td>
<td>-0.051</td>
<td>0.180</td>
</tr>
<tr class="odd">
<td>5</td>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>272</td>
<td>72</td>
<td>69</td>
<td>26.5%</td>
<td>25.4%</td>
<td>0.011</td>
<td>-0.114</td>
<td>0.133</td>
</tr>
<tr class="even">
<td>6</td>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>274</td>
<td>55</td>
<td>56</td>
<td>20.1%</td>
<td>20.4%</td>
<td>-0.004</td>
<td>-0.111</td>
<td>0.107</td>
</tr>
<tr class="odd">
<td>7</td>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td>266</td>
<td>23</td>
<td>55</td>
<td>8.6%</td>
<td>20.7%</td>
<td>-0.120</td>
<td>-0.202</td>
<td>-0.041</td>
</tr>
<tr class="even">
<td>8</td>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td>273</td>
<td>33</td>
<td>90</td>
<td>12.1%</td>
<td>33.0%</td>
<td>-0.209</td>
<td>-0.302</td>
<td>-0.105</td>
</tr>
<tr class="odd">
<td>9</td>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td>272</td>
<td>43</td>
<td>101</td>
<td>15.8%</td>
<td>37.1%</td>
<td>-0.213</td>
<td>-0.328</td>
<td>-0.102</td>
</tr>
<tr class="even">
<td>10</td>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td>267</td>
<td>33</td>
<td>111</td>
<td>12.4%</td>
<td>41.6%</td>
<td>-0.292</td>
<td>-0.397</td>
<td>-0.189</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The ranked table shows a clear spread in student preferences. Classes with positive scores were selected as best more often than worst, while classes with negative scores were selected as worst more often than best.</p>
<div id="cell-counts-analysis-plot" class="cell" data-fig-height="6" data-fig-width="10" data-message="false" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/counts-analysis-plot-output-1.png" id="counts-analysis-plot" width="948" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-counts-analysis-written-summary" class="cell" data-message="false" data-execution_count="8">
<div id="counts-analysis-written-summary" class="cell-output cell-output-display cell-output-markdown">
<p>The most preferred class by the simple counts score is <strong>MGTA 495 Marketing Analytics (Spring with Yavorsky)</strong>, with a score of <strong>0.493</strong>. The top three classes are <strong>MGTA 495 Marketing Analytics (Spring with Yavorsky) (0.493), MGTA 453 Business Analytics (Fall with August) (0.141), MGTA 455 Customer Analytics (Winter with Nijs) (0.120)</strong>. At the bottom of the ranking, the least preferred class is <strong>MGTA 444 Analytics Consulting (Winter with Peterson)</strong>, with a score of <strong>-0.292</strong>. The three lowest-ranked classes are <strong>MGTA 444 Analytics Consulting (Winter with Peterson) (-0.292), MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin) (-0.213), MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs) (-0.209)</strong>. Overall, the counts analysis gives a simple and intuitive first look at the data: some classes are clearly preferred, some are clearly less preferred, and the middle group is closer together.</p>
</div>
</div>
</div>
</section>
<section id="from-maxdiff-data-to-mnl-choices" class="level2">
<h2 class="anchored" data-anchor-id="from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</h2>
<div class="callout-">
<p>The MaxDiff responses can be treated as multinomial logit choice data. In each task, a respondent sees four classes and makes two choices. First, they choose the class they like the most from the full set of four. Then, after the best class is removed, they choose the class they like the least from the remaining three.</p>
<p>For the best-choice part, the MNL model assigns each item <span class="math inline">\(j\)</span> a utility coefficient <span class="math inline">\(\beta_j\)</span>. If the task shows items <span class="math inline">\(\{a,b,c,d\}\)</span>, the probability that item <span class="math inline">\(b\)</span> is chosen as best is:</p>
<p><span class="math display">\[
P(\text{best}=b)
=
\frac{\exp(\beta_b)}
{\exp(\beta_a)+\exp(\beta_b)+\exp(\beta_c)+\exp(\beta_d)}
\]</span></p>
<p>For the worst-choice part, I use the same utilities but flip the sign. Intuitively, an item with high positive utility should be unlikely to be selected as worst, while an item with low utility should be more likely to be selected as worst. If item <span class="math inline">\(b\)</span> was already selected as best, then the probability that item <span class="math inline">\(c\)</span> is selected as worst from the remaining items is:</p>
<p><span class="math display">\[
P(\text{worst}=c \mid \text{best}=b)
=
\frac{\exp(-\beta_c)}
{\exp(-\beta_a)+\exp(-\beta_c)+\exp(-\beta_d)}
\]</span></p>
<p>Therefore, each MaxDiff task contributes two MNL choice observations: one best-choice observation from four alternatives, and one worst-choice observation from the remaining three alternatives.</p>
<p>The model also needs a normalization for identification. Adding the same constant to every <span class="math inline">\(\beta_j\)</span> would not change any of the MNL probabilities, so the absolute level of utility is not identified. I set <span class="math inline">\(\beta_1 = 0\)</span> and estimate the remaining nine coefficients, <span class="math inline">\(\beta_2,\ldots,\beta_{10}\)</span>, relative to item 1.</p>
<div id="reshape-maxdiff-to-mnl" class="cell" data-message="false" data-execution_count="9">
<div id="reshape-maxdiff-to-mnl-1" class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Choice observation</th>
<th data-quarto-table-cell-role="th">Number of observations</th>
<th data-quarto-table-cell-role="th">Minimum alternatives</th>
<th data-quarto-table-cell-role="th">Maximum alternatives</th>
<th data-quarto-table-cell-role="th">Chosen alternatives per observation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Best choice</td>
<td>680</td>
<td>4</td>
<td>4</td>
<td>1.0</td>
</tr>
<tr class="even">
<td>Worst choice</td>
<td>680</td>
<td>3</td>
<td>3</td>
<td>1.0</td>
</tr>
</tbody>
</table>
</div>
<div id="reshape-maxdiff-to-mnl-2" class="cell-output cell-output-display cell-output-markdown">
<p>After reshaping, the <strong>680 valid MaxDiff tasks</strong> become <strong>1,360 MNL choice observations</strong>: one best-choice observation and one worst-choice observation for each task. This task-level structure will be used in the likelihood function in the next section.</p>
</div>
</div>
</div>
</section>
<section id="mnl-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-maximum-likelihood">MNL via Maximum Likelihood</h2>
<div class="callout-">
<p>Next, I estimate the MNL model by maximum likelihood. Each item has a utility coefficient <span class="math inline">\(\beta_j\)</span>, with item 1 used as the reference category. Therefore, I set <span class="math inline">\(\beta_1 = 0\)</span> and estimate the remaining nine coefficients.</p>
<p>For each MaxDiff task, the log-likelihood combines the probability of the best choice and the probability of the worst choice. The log-likelihood is:</p>
<p><span class="math display">\[
\ell(\boldsymbol{\beta})
=
\sum_{\text{tasks}}
\left[
\beta_{j_b^*}
-
\log \sum_{j \in \text{shown}} \exp(\beta_j)
-
\beta_{j_w^*}
-
\log \sum_{j \in \text{shown} \setminus \{j_b^*\}} \exp(-\beta_j)
\right]
\]</span></p>
<p>where <span class="math inline">\(j_b^*\)</span> is the item chosen as best and <span class="math inline">\(j_w^*\)</span> is the item chosen as worst. I maximize this log-likelihood using BFGS. For interpretation, I also convert the utility estimates into shares of preference:</p>
<p><span class="math display">\[
\hat{s}_j
=
\frac{\exp(\hat{\beta}_j)}
{\sum_{k=1}^{10} \exp(\hat{\beta}_k)}
\]</span></p>
<p>These shares can be interpreted as the model-implied probability that each class would be chosen if all 10 classes appeared together on one screen.</p>
<div id="mle-standard-errors" class="cell" data-message="false" data-execution_count="11">
<div id="mle-standard-errors-1" class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">MLE rank</th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Beta hat</th>
<th data-quarto-table-cell-role="th">SE</th>
<th data-quarto-table-cell-role="th">Share of preference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td>1.630</td>
<td>0.146</td>
<td>28.4%</td>
</tr>
<tr class="even">
<td>2</td>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.744</td>
<td>0.142</td>
<td>11.7%</td>
</tr>
<tr class="odd">
<td>3</td>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.656</td>
<td>0.142</td>
<td>10.7%</td>
</tr>
<tr class="even">
<td>4</td>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.555</td>
<td>0.140</td>
<td>9.7%</td>
</tr>
<tr class="odd">
<td>5</td>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.443</td>
<td>0.140</td>
<td>8.7%</td>
</tr>
<tr class="even">
<td>6</td>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.438</td>
<td>0.137</td>
<td>8.6%</td>
</tr>
<tr class="odd">
<td>7</td>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td>0.236</td>
<td>0.137</td>
<td>7.0%</td>
</tr>
<tr class="even">
<td>8</td>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td>0.000</td>
<td>Reference</td>
<td>5.6%</td>
</tr>
<tr class="odd">
<td>9</td>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td>-0.067</td>
<td>0.139</td>
<td>5.2%</td>
</tr>
<tr class="even">
<td>10</td>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td>-0.239</td>
<td>0.141</td>
<td>4.4%</td>
</tr>
</tbody>
</table>
</div>
<div id="mle-standard-errors-2" class="cell-output cell-output-display cell-output-markdown">
<p>The MNL model converged successfully. The maximized log-likelihood is <strong>-1572.73</strong>.</p>
</div>
</div>
<p>The table reports the estimated MNL utilities, standard errors, and model-implied shares of preference. Since <span class="math inline">\(\beta_1\)</span> is fixed to zero, all other utility coefficients are interpreted relative to item 1.</p>
<div id="cell-mle-share-plot" class="cell" data-fig-height="6" data-fig-width="10" data-message="false" data-execution_count="12">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/mle-share-plot-output-1.png" id="mle-share-plot" width="948" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="mle-vs-counts-comparison" class="cell" data-message="false" data-execution_count="13">
<div id="mle-vs-counts-comparison-1" class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Counts score</th>
<th data-quarto-table-cell-role="th">Counts rank</th>
<th data-quarto-table-cell-role="th">MLE share</th>
<th data-quarto-table-cell-role="th">MLE rank</th>
<th data-quarto-table-cell-role="th">Counts rank minus MLE rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td>0.493</td>
<td>1</td>
<td>28.4%</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.141</td>
<td>2</td>
<td>11.7%</td>
<td>2</td>
<td>0</td>
</tr>
<tr class="odd">
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.120</td>
<td>3</td>
<td>10.7%</td>
<td>3</td>
<td>0</td>
</tr>
<tr class="even">
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.062</td>
<td>4</td>
<td>9.7%</td>
<td>4</td>
<td>0</td>
</tr>
<tr class="odd">
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.011</td>
<td>5</td>
<td>8.7%</td>
<td>5</td>
<td>0</td>
</tr>
<tr class="even">
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>-0.004</td>
<td>6</td>
<td>8.6%</td>
<td>6</td>
<td>0</td>
</tr>
<tr class="odd">
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td>-0.120</td>
<td>7</td>
<td>7.0%</td>
<td>7</td>
<td>0</td>
</tr>
<tr class="even">
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td>-0.209</td>
<td>8</td>
<td>5.6%</td>
<td>8</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td>-0.213</td>
<td>9</td>
<td>5.2%</td>
<td>9</td>
<td>0</td>
</tr>
<tr class="even">
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td>-0.292</td>
<td>10</td>
<td>4.4%</td>
<td>10</td>
<td>0</td>
</tr>
</tbody>
</table>
</div>
<div id="mle-vs-counts-comparison-2" class="cell-output cell-output-display cell-output-markdown">
<p>The MLE ranking is identical to the simple counts ranking. This is not too surprising because the MaxDiff design is fairly balanced, so the counts score already captures much of the preference ordering. The MNL model adds a formal choice model and converts the ranking into interpretable preference shares. The highest MLE share belongs to <strong>MGTA 495 Marketing Analytics (Spring with Yavorsky)</strong> with a share of <strong>28.4%</strong>. The lowest MLE share belongs to <strong>MGTA 444 Analytics Consulting (Winter with Peterson)</strong> with a share of <strong>4.4%</strong>.</p>
</div>
</div>
</div>
</section>
<section id="mnl-via-bayesian-estimation" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-bayesian-estimation">MNL via Bayesian Estimation</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Now fit the same MNL model by <span class="text-magenta"><strong>Bayesian methods</strong></span>. Reference the week-7 slides on Bayes’ rule and the random-walk Metropolis-Hastings sampler.</p></li>
<li><p>The posterior over <span class="math inline">\(\boldsymbol{\beta}\)</span> is</p></li>
</ul>
<p><span class="math display">\[
\pi(\boldsymbol{\beta} \mid \boldsymbol{y}) \;\propto\; L(\boldsymbol{\beta}) \cdot \pi(\boldsymbol{\beta})
\]</span></p>
<p>Use a weakly informative multivariate normal prior: <span class="math inline">\(\boldsymbol{\beta} \sim N(\boldsymbol{0},\; 10 \cdot I)\)</span>. (SD <span class="math inline">\(\approx 3.2\)</span> on each <span class="math inline">\(\beta\)</span> is plenty diffuse without being absurd.)</p>
<ul>
<li>Code a random-walk Metropolis sampler. The skeleton is:</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>log_post <span class="ot">&lt;-</span> <span class="cf">function</span>(beta) <span class="fu">ll</span>(beta, ...) <span class="sc">+</span> <span class="fu">sum</span>(<span class="fu">dnorm</span>(beta, <span class="dv">0</span>, <span class="fu">sqrt</span>(<span class="dv">10</span>), <span class="at">log =</span> <span class="cn">TRUE</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>mh <span class="ot">&lt;-</span> <span class="cf">function</span>(beta0, n_iter, step) {</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  K <span class="ot">&lt;-</span> <span class="fu">length</span>(beta0)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  draws <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, n_iter, K)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  beta  <span class="ot">&lt;-</span> beta0</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  lp    <span class="ot">&lt;-</span> <span class="fu">log_post</span>(beta)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  accept <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (t <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_iter) {</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    beta_star <span class="ot">&lt;-</span> beta <span class="sc">+</span> <span class="fu">rnorm</span>(K, <span class="dv">0</span>, step)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    lp_star   <span class="ot">&lt;-</span> <span class="fu">log_post</span>(beta_star)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">log</span>(<span class="fu">runif</span>(<span class="dv">1</span>)) <span class="sc">&lt;</span> lp_star <span class="sc">-</span> lp) {</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>      beta <span class="ot">&lt;-</span> beta_star; lp <span class="ot">&lt;-</span> lp_star; accept <span class="ot">&lt;-</span> accept <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    draws[t, ] <span class="ot">&lt;-</span> beta</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">draws =</span> draws, <span class="at">accept_rate =</span> accept <span class="sc">/</span> n_iter)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><p>Run the sampler for ~20,000 iterations (or more if you have patience). Discard the first 25% as burn-in.</p></li>
<li><p><span class="text-blue"><strong>Tune the step size</strong></span> to land at an acceptance rate of roughly 25–40%. If acceptance is too low, halve the step; too high, double it. <em>(See week-7 “Tuning the Step Size” slide.)</em></p></li>
<li><p>Run diagnostics: report the final acceptance rate, plot the trace for at least 2–3 of the <span class="math inline">\(\beta\)</span> parameters (you should see a “fuzzy caterpillar,” not a slow drift), and confirm that the chain has stabilized after burn-in.</p></li>
<li><p>Compute and report:</p>
<ul>
<li>Posterior <strong>mean</strong> <span class="math inline">\(\hat\beta_j\)</span> for each item</li>
<li>95% <strong>credible interval</strong> <span class="math inline">\([2.5\%,\, 97.5\%]\)</span> percentiles of the post-burn-in draws</li>
<li>Posterior shares of preference: for each MCMC draw, compute <span class="math inline">\(\hat s_j^{(s)} = \exp(\hat\beta_j^{(s)}) / \sum_k \exp(\hat\beta_k^{(s)})\)</span>, then take the posterior mean of the <span class="math inline">\(\hat s_j^{(s)}\)</span> across draws.</li>
</ul></li>
<li><p>Display a table with item, posterior mean <span class="math inline">\(\beta\)</span>, 95% CI, posterior mean share. Plot the shares with the credible interval as error bars.</p></li>
<li><p>Compare to the MLE results: posterior means should be close to the MLE point estimates; posterior SDs should be close to the MLE standard errors. Where do they differ noticeably? Why?</p></li>
</ul>
</div>
</div>
</section>
<section id="comparing-the-three-methods" class="level2">
<h2 class="anchored" data-anchor-id="comparing-the-three-methods">Comparing the Three Methods</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Create a single side-by-side comparison of all three analyses. Suggested format: a table with columns</p>
<ul>
<li>Item / class label</li>
<li>Counts score (% best − % worst)</li>
<li>Counts rank</li>
<li>MLE share of preference, MLE rank</li>
<li>Bayes posterior-mean share, Bayes rank</li>
</ul>
<p>Sorted by one of the rankings (e.g., MLE rank).</p></li>
<li><p>Also create a visual comparison: three horizontal bar charts side-by-side, one per method, each showing items sorted by that method’s score/share. Color-code consistently so the reader can trace a single class across all three panels.</p></li>
<li><p>Write a paragraph discussing the comparison:</p>
<ul>
<li>Where do the three methods <em>agree</em>? Almost always at the top and bottom of the ranking.</li>
<li>Where do they <em>disagree</em> — and why? Often in the middle, where items have similar utility and small noise can flip rankings.</li>
<li>What does the MNL add over the counts analysis? <em>(Hint: it models the choice process explicitly — every “shown” item contributes information about </em>not* being picked, not just the picks themselves.)*</li>
<li>What does Bayes add over MLE? <em>(Hint: credible intervals on derived quantities like shares of preference are easy — just push every MCMC draw through the soft-max and take quantiles. Doing this from an MLE requires the delta method.)</em></li>
</ul></li>
</ul>
</div>
</div>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Close with a short discussion section that synthesizes the analysis for a non-technical reader (think: an academic advisor or a student deciding which classes to take). Cover:</p>
<ul>
<li><p>The substantive finding — which MSBA classes do students prefer most? Are there any surprises?</p></li>
<li><p>The methodological finding — for what kind of question would you reach for each of the three methods?</p>
<ul>
<li><em>Counts</em>: quick descriptive summary, useful for an executive dashboard</li>
<li><em>MLE MNL</em>: rigorous point estimates with classical standard errors; good when you need a single number to report</li>
<li><em>Bayesian MNL</em>: when you want uncertainty on derived quantities (shares, market simulations, “what if we added a new class?” scenarios), or when you want to extend the model hierarchically to estimate individual-level preferences</li>
</ul></li>
<li><p>Caveats: the survey was on a self-selected sample of MSBA students; preferences may not generalize beyond this group. Item presentation order, prior coursework, and current standing in the program may all affect responses.</p></li>
</ul></li>
<li><p>End with one or two sentences on what you would do differently or explore next if you had more time.</p></li>
</ul>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>